##Importing the libraries

In [1]:
import numpy as np
import pandas as pd

##Data preprocessing

In [2]:
train_set = pd.read_csv('train.csv')
test_set = pd.read_csv('test.csv')

In [3]:
train_set.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [4]:
train_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42000 entries, 0 to 41999
Columns: 785 entries, label to pixel783
dtypes: int64(785)
memory usage: 251.5 MB


In [5]:
X = train_set.iloc[:, 1:].values
y = train_set.iloc[:, 0].values

In [6]:
print(y)

[1 0 1 ... 7 6 9]


In [7]:
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


##Splitting the dataset into the Training set and Test set

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

##Training the Kernel SVM model on train_set

In [9]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

##Making the Confusion Matrix

In [10]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[847   0   0   0   1   2   3   0   0   0]
 [  0 934   1   3   0   0   0   0   2   0]
 [  1   1 817   1   2   0   2   5   5   1]
 [  1   0   8 841   0  11   0   4   5   3]
 [  0   1   2   0 813   0   1   4   0   8]
 [  2   1   0  10   0 712   3   0   1   2]
 [  3   0   1   0   4   3 789   0   0   0]
 [  0   3   4   0   3   0   0 830   0  10]
 [  1   5   0   2   4   5   3   1 822   3]
 [  4   1   1   3  11   2   0   8   2 811]]


0.9780952380952381

## Test set prediction

In [11]:
Xt = test_set.iloc[:].values

In [12]:
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X, y)

prediction = classifier.predict(Xt)

##Submission

In [24]:
submission=pd.read_csv('sample_submission.csv')
submission['Label']=prediction
submission.to_csv('submission.csv', index=False)

In [25]:
submission = pd.read_csv('submission.csv')
submission.head()

ImageId  Label
0        1      2
1        2      0
2        3      9
3        4      9
4        5      3